name: Build TVBox APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /home/runner/Android/Sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Download Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2
        ndk: 25.2.9519653

    - name: Create local.properties
      run: |
        echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
        echo "ndk.dir=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> local.properties

    - name: Grant Gradle executable permissions
      run: chmod +x ./gradlew

    - name: Clean and assemble release APK
      run: ./gradlew clean assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: TVBox-APK
        path: app/build/outputs/apk/release/*.apk
